// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ACS.AMS.DAL.DBModel
{
    public partial class prc_GetAssetDetailsResult
    {
        public int? LocationTypeID { get; set; }
        public int? L2LocationID { get; set; }
        public int? CategoryTypeID { get; set; }
    }
}
