// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ACS.AMS.DAL.DBModel
{
    public partial class prc_ExportToCategoryResult
    {
        public string? L1CategoryCode { get; set; }
        public string? L1Desc { get; set; }
        public string? L2CategoryCode { get; set; }
        public string? L2Desc { get; set; }
        public string? L3CategoryCode { get; set; }
        public string? L3Desc { get; set; }
        public string? L4CategoryCode { get; set; }
        public string? L4Desc { get; set; }
        public string? L5CategoryCode { get; set; }
        public string? L5Desc { get; set; }
        public string? L6CategoryCode { get; set; }
        public string? L6Desc { get; set; }
    }
}
