// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ACS.AMS.DAL.DBModel
{
    public partial class prc_GetPeriodWithDateResult
    {
        public int PeriodID { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string PeriodName { get; set; } = default!;
        public string? Status { get; set; }
        public int periodYear { get; set; }
        public int lastField { get; set; }
        public int nextRecord { get; set; }
    }
}
