// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ACS.AMS.DAL.DBModel
{
    public partial class prc_ExportToLocationResult
    {
        public string? L1LocCode { get; set; }
        public string? L1Desc { get; set; }
        public string? L2LocCode { get; set; }
        public string? L2Desc { get; set; }
        public string? L3LocCode { get; set; }
        public string? L3Desc { get; set; }
        public string? L4locCode { get; set; }
        public string? L4Desc { get; set; }
        public string? L5locCode { get; set; }
        public string? L5Desc { get; set; }
        public string? L6locCode { get; set; }
        public string? L6Desc { get; set; }
    }
}
