// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ACS.AMS.DAL.DBModel
{
    public partial class prc_DepreciationApprovalResult
    {
        public string PeriodName { get; set; } = default!;
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string status { get; set; } = default!;
        public int PeriodID { get; set; }
        public int DepreciationID { get; set; }
    }
}
