// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ACS.AMS.DAL.DBModel;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ACS.AMS.DAL.DBContext
{
    public partial interface IAMSContextProcedures
    {
        Task<List<Prc_AssetCreationValidationResult>> Prc_AssetCreationValidationAsync(int? UserID, string CategoryCode, string LocationCode, int? CategoryID, int? LocationID, int? DepartmentID, string DepartmentCode, string SerialNo, string ManufacturerCode, int? ManufacturerID, string DataProcessedBy, OutputParameter<int?> ErrorID, OutputParameter<string> ErrorMsg, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Prc_AssetModificationValidationResult>> Prc_AssetModificationValidationAsync(int? UserID, int? AssetID, string CategoryCode, string LocationCode, int? CategoryID, int? LocationID, int? DepartmentID, string DepartmentCode, string SerialNo, string ManufacturerCode, int? ManufacturerID, string DataProcessedBy, OutputParameter<int?> ErrorID, OutputParameter<string> ErrorMsg, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_AssetRetirementForApprovalResult>> prc_AssetRetirementForApprovalAsync(int? UserID, int? ApprovalID, int? CompanyID, int? LanguageID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Prc_AssetRetirementValidationResult>> Prc_AssetRetirementValidationAsync(int? UserID, int? AssetID, string DataProcessedBy, OutputParameter<int?> ErrorID, OutputParameter<string> ErrorMsg, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_AssetTransferForApprovalResult>> prc_AssetTransferForApprovalAsync(int? UserID, int? ApprovalID, int? CompanyID, int? LanguageID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Prc_AssetTransferValidationResult>> Prc_AssetTransferValidationAsync(int? UserID, int? AssetID, string LocationCode, int? LocationID, int? DepartmentID, string DepartmentCode, string DataProcessedBy, OutputParameter<int?> ErrorID, OutputParameter<string> ErrorMsg, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_DepreciationResult>> prc_DepreciationAsync(int? PeriodID, int? UserID, int? CompanyID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_DepreciationApprovalResult>> prc_DepreciationApprovalAsync(int? userID, int? CompanyID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_ExportToCategoryResult>> prc_ExportToCategoryAsync(int? UserID, string FilterData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_ExportToLocationResult>> prc_ExportToLocationAsync(int? UserID, string FilterData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_GetAssetDetailsResult>> prc_GetAssetDetailsAsync(int? LocationID, int? CategoryID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_GetPeriodWithDateResult>> prc_GetPeriodWithDateAsync(int? CompanyID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_GetSecondLevelLocationValueResult>> prc_GetSecondLevelLocationValueAsync(int? LocationID, string AssetIDS, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<prc_ImportTemplateUserAgainstListResult>> prc_ImportTemplateUserAgainstListAsync(int? UserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Prc_ValidateAssetAdditionAsync(int? LocationID, int? CategoryID, OutputParameter<int?> ErrorID, OutputParameter<string> ErrorMessage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Prc_ValidateBulkAssetAdditionAsync(string LocationCode, string CategoryCode, OutputParameter<int?> ErrorID, OutputParameter<string> ErrorMessage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Prc_ValidateBulkExcelRetirementAsync(string Barcode, int? UserID, OutputParameter<int?> ErrorID, OutputParameter<string> ErrorMessage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> prc_ValidateForTransactionAsync(string FromAssetID, int? ToLocationID, int? ModuleID, string RightName, OutputParameter<int?> ErrorID, OutputParameter<string> ErrorMessage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Prc_ValidateUserWiseTransactionsResult>> Prc_ValidateUserWiseTransactionsAsync(int? UserID, int? ModuleID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
